AWSTemplateFormatVersion: '2010-09-09'
Resources:

  LoginFailureEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: LoginFailureEventRule
      EventPattern:
        source:
          - "aws.signin"
        detail-type:
          - "AWS Console Sign In via CloudTrail"
        detail:
          eventSource:
            - "signin.amazonaws.com"
          responseElements:
            ConsoleLogin:
              - "Failure"
      Targets:
        - Arn: !Sub "arn:aws:events:us-east-1:${AWS::AccountId}:event-bus/CrossRegionLoginFailuresEventBus"
          Id: "CrossRegionLoginFailuresEventBus"
          RoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/EventBridgeTargetRole"